### PR TITLE
switching from log facade to tracing

### LINKED ISSUE #283: Consider switching from log facade to tracing
It might be nice to switch to the [`tracing`](https://crates.io/crates/tracing) crate due to its excellent async integration and the ability to trace the progress of individual futures. However, we should probably listen to user feedback to determine whether it provides enough value over `log` to warrant switching, since this has the potential to be a disruptive change. Anyone hold an opinion on this?

### PR DESCRIPTION
**Pull request by attila-lin**
fix  #283

### CODE REVIEW

**Comment by ebkalderon** [comment]
This looks good to me, as an initial effort! It would be great if we could leverage the futures instrumentation facilities of `tracing` as well going forward. Thanks for the pull request, @attila-lin.

Would you mind fixing the conflicts in the `CHANGELOG.md` and `Cargo.toml` as a result of the recent release of 0.17.0, please?

**Comment by attila-lin** [comment]
Yes. I will fix it.

**Comment by attila-lin** [comment]
@ebkalderon done 😄

**Review by ebkalderon — APPROVED** [review]
Looks great! Thanks for getting this PR working. :heart: 

One final request: it seems that #312 has introduced merge conflicts in the `Cargo.toml` and `CHANGELOG.md` again. Would you perhaps mind rebasing your branch one last time? Apologies, and thanks again for your contribution.

**Comment by attila-lin** [comment]
done. @ebkalderon

**Comment by silvanshade** [comment]
Thanks for the PR and for your patience getting this merged!

**Pull request merged**
