### PR TITLE
Tweak grammar around "for example"

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Review by ebkalderon — APPROVED** [review]
Looks good to me! Do you think you could open a similar PR at [microsoft/language-server-protocol](https://github.com/microsoft/language-server-protocol), which is where I originally sourced this help text?

**Comment by brettcannon** [comment]
> Looks good to me! Do you think you could open a similar PR at [microsoft/language-server-protocol](https://github.com/microsoft/language-server-protocol), which is where I originally sourced this help text?

Definitely! I'm actually the dev manager for the Python experience in VS Code, so Dirk is a teammate of mine. 😁

BTW, my team is also in charge of https://github.com/microsoft/lsprotocol , so if you would ever be interested in having the LSP types auto-generated from the spec for Rust, please feel free to reach out!

**Comment by brettcannon** [comment]
https://github.com/microsoft/language-server-protocol/pull/1626

**Comment by ebkalderon** [comment]
Love this idea, @brettcannon! It would be awesome to have the protocol types generated first-party and on a regular release schedule rather than being manually updated, as with the [lsp-types](https://github.com/gluon-lang/lsp-types) crate currently. I may be in touch about that.

For now, I'd be happy to merge this PR as-is. Thanks for the contribution!

**Comment by brettcannon** [comment]
> I may be in touch about that.

Please do! We wanted to get the Python-generated types working appropriately for https://pypi.org/project/pygls/ before we reached out to anyone else, and that _just_ got confirmed this month. So good timing on all of this. 😁

**Comment by ebkalderon** [comment]
@brettcannon Awesome! I'm definitely down to help build a Rust implementation, if you're still open. I reached out to you with a DM on Mastodon (@ebkalderon@hachyderm.io). Feel free to reply there so we can figure out where would be the most appropriate place online to take this conversation online!

**Pull request merged**
