### PR TITLE
Add default implementations for methods in LanguageServer trait

### PR DESCRIPTION
**Pull request by icsaszar**
Implements changes outlined in #100.

@ebkalderon Should I also remove the unused methods from the examples (in lib.rs and examples folder)?

### CODE REVIEW

**Comment by ebkalderon** [comment]
Sure, feel free to remove any unnecessary methods from the examples that don't have any custom functionality! I believe the `server.rs` example demonstrates the use of `printer.log_message()` and `printer.apply_edit()` in a few places, so those should likely remain intact.

Also, I'd recommend we not log an error for unused notifications. Since servers are not required by the Language Server Protocol spec to respect notifications from the client, I don't think it makes sense to log an `error!()` if they are unused.

**Comment by icsaszar** [comment]
In was thinking that notifications are opt-in by the server (it has to declare the capability to get them) so there is a possibility that the client forgot the implementation.

From the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_synchronization_cc):

> Client support for textDocument/open, textDocument/change and textDocument/close notifications is mandatory in the protocol and clients can not opt out supporting them. In addition a server must either implement all three of them or none. Their capabilities are therefore controlled via a combined client and server capability.
> Client Capability:
> property path (optional): textDocument.synchronization.dynamicRegistration
> property type: boolean
> Controls whether text document synchronization supports dynamic registration.
> Server Capability:
> property path (optional): textDocumentSync
> property type: TextDocumentSyncKind | TextDocumentSyncOptions. The below definition of the TextDocumentSyncOptions only covers the properties specific to the open, change and close notifications.

I would still go with a warning, but I'll leave it to you to decide.

**Comment by ebkalderon** [comment]
Hmm, this may be true for the three `textDocument` notifications mentioned above, but there doesn't appear to be any similar stipulation for other notifications. Additionally, since the specification allows for the server to potentially support either all or none of the above three, I think it might be best to emit a `warn!()` rather than `error!()` for that reason, since it's not guaranteed to be an error. I think that the other notifications should not log `error!()` messages either and can be silently ignored if unspecified because, semantically, the server intentionally chose to silently discard them if it provides no method implementation.

**Comment by icsaszar** [comment]
I changed every notification to `warn!()`, but I agree that it's a bit cumbersome in the case when the server wants to just silently ignore them.

**Comment by icsaszar** [comment]
Should be fixed now. 

I forgot to mention I also added some logic to the example in lib.rs since now we can skip the default implementations.

**Comment by ebkalderon** [comment]
No worries about the example logic that was added to `lib.rs`, haha. I think it makes for a great showcase. 😄

**Pull request merged**
